MACOSX_DEPLOYMENT_TARGET:
- '11.0'
aws_sdk_cpp:
- 1.8.186
bzip2:
- '1'
c_compiler:
- clang
c_compiler_version:
- '11'
channel_sources:
- conda-forge/label/rust_dev,conda-forge
channel_targets:
- conda-forge main
cuda_compiler_version:
- None
cxx_compiler:
- clangxx
cxx_compiler_version:
- '11'
gflags:
- '2.2'
glog:
- '0.5'
grpc_cpp:
- '1.38'
libprotobuf:
- '3.16'
lz4_c:
- 1.9.3
macos_machine:
- arm64-apple-darwin20.0.0
numpy:
- '1.19'
orc:
- 1.6.8
pin_run_as_build:
  bzip2:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  zlib:
    max_pin: x.x
python:
- 3.8.* *_cpython
re2:
- 2021.06.01
snappy:
- '1'
target_platform:
- osx-arm64
thrift_cpp:
- 0.14.2
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
- - python
  - numpy
zlib:
- '1.2'
zstd:
- '1.5'
