aws_sdk_cpp:
- 1.8.186
bzip2:
- '1'
c_compiler:
- vs2017
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cuda_compiler:
- nvcc
cuda_compiler_version:
- None
cxx_compiler:
- vs2017
gflags:
- '2.2'
glog:
- '0.5'
grpc_cpp:
- '1.38'
libprotobuf:
- '3.16'
lz4_c:
- 1.9.3
numpy:
- '1.19'
pin_run_as_build:
  bzip2:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  zlib:
    max_pin: x.x
python:
- 3.9.* *_cpython
re2:
- 2021.06.01
snappy:
- '1'
target_platform:
- win-64
thrift_cpp:
- 0.14.2
zip_keys:
- - numpy
  - python
zlib:
- '1.2'
zstd:
- '1.5'
