name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test -count 1 -bench . -benchtime 1x ./...

      - name: Test with -tags purego
        run: go test -count 1 -bench . -benchtime 1x -tags purego ./...

# TODO: Test on other architectures. Unfortunately only amd64 is supported
# by GH Actions. We could use QEMU in the meantime.
